# Generated by Django 3.1.4 on 2021-11-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(default=0, max_length=32),
        ),
    ]
